In [1]:
import pandas as pd

In [30]:
orders=pd.read_csv(r"D:\ai_customer_intelligence\data\olist_orders_dataset.csv")
items=pd.read_csv(r"D:\ai_customer_intelligence\data\olist_order_items_dataset.csv")
products=pd.read_csv(r"D:\ai_customer_intelligence\data\olist_products_dataset.csv")
reviews=pd.read_csv(r"D:\ai_customer_intelligence\data\cleaned_reviews_dataset.csv")
translation=pd.read_csv(r"D:\ai_customer_intelligence\data\product_category_name_translation.csv")

In [31]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [32]:
orders=orders[['order_id','customer_id','order_status','order_purchase_timestamp']]
orders

,order_id,customer_id,order_status,order_purchase_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39
...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30

In [33]:
products=products[['product_id','product_category_name']]
products

                             product_id              product_category_name
0      1e9e8ef04dbcff4541ed26657ea517e5                         perfumaria
1      3aa071139cb16b67ca9e5dea641aaa2f                              artes
2      96bd76ec8810374ed1b65e291975717f                      esporte_lazer
3      cef67bcfe19066a932b7673e239eb23d                              bebes
4      9dc1a7de274444849c219cff195d0b71              utilidades_domesticas
...                                 ...                                ...
32946  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao
32947  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao
32948  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho
32949  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios
32950  106392145fca363410d287a815be6de4                    cama_mesa_banho

[32951 rows x 2 columns]

In [34]:
items=items[['order_id','product_id','price']]
items

,order_id,product_id,price
0,00010242fe8c5a6d1ba2dd792cb16214,4244733e06e7ecb4970a6e2683c13e61,58.90
1,00018f77f2f0320c557190d7a144bdd3,e5f2d52b802189ee658865ca93d83a8f,239.90
2,000229ec398224ef6ca0657da4fc703e,c777355d18b72b67abbeef9df44fd0fd,199.00
3,00024acbcdf0a6daa1e931b038114c75,7634da152a4610f1595efa32f14722fc,12.99
4,00042b26cf59d7ce69dfabb4e55b4fd9,ac6c3623068f30de03045865e4e10089,199.90
...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,4aa6014eceb682077f9dc4bffebc05b0,299.99
112646,fffcd46ef2263f404302a634eb57f7eb,32e07fd915822b0765e448c4dd74c828,350.00
112647,fffce4705a9662cd70adb13d4a31832d,72a30483855e2eafc67aee5dc2560482,99.90
112648,fffe18544ffabc95dfada21779c9644f,9c422a519119dcad7575db5af1ba540e,55.99
112649,fffe41c64501cc87c801fd61db3f6244,350688d9dc1e75ff97be326363655e01,43.00

In [35]:
reviews=reviews[['order_id','review_score','review_clean']]
reviews

,order_id,review_score,review_clean
0,658677c97b385a9be170737859d3511b,5,recebi bem antes do prazo estipulado.
1,8e6bfb81e283fa7e4f11123a3fb894f1,5,parabéns lojas lannister adorei comprar pela i...
2,b9bf720beb4ab3728760088589c62129,4,aparelho eficiente. no site marca do aparelho ...
3,9d6f15f95d01e79bd1349cc208361f09,4,"mas um pouco ,travando..pelo valor ta boa."
4,e51478e7e277a83743b6f9991dbfa3fb,5,"vendedor confiável, produto ok entrega antes d..."
...,...,...,...
40786,d398e9c82363c12527f71801bf0e6100,4,para este produto recebi de acordo com compra ...
40787,509b86c65fe4e2ad5b96408cfef9755e,5,entregou dentro do prazo. produto chegou em co...
40788,d5cb12269711bd1eaf7eed8fd32a7c95,3,"produto não foi enviado com nf, não existe ven..."
40789,55d4004744368f5571d1f590031933e4,5,"excelente mochila, entrega super rápida. super..."
40790,90531360ecb1eec2a1fbb265a0db0508,1,"meu produto chegou ja tenho que devolver, pois..."

In [36]:
reviews=reviews.rename(columns={'review_score':'score','review_clean':'comment'})

In [37]:
reviews.isna().sum()

order_id     0
score        0
comment     52
dtype: int64

In [38]:
reviews=reviews.dropna(subset=['comment'])

In [39]:
reviews.shape

(40739, 3)

In [40]:
translation

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [41]:
products=products.merge(translation,on='product_category_name',how='left')
products

,product_id,product_category_name,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,housewares
...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,furniture_decor
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,construction_tools_lights
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,bed_bath_table
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,computers_accessories
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,bed_bath_table

In [42]:
master=orders.merge(items,on='order_id').merge(products,on='product_id').merge(reviews,on='order_id',how='left')
master

,order_id,customer_id,order_status,order_purchase_timestamp,product_id,price,product_category_name,product_category_name_english,score,comment
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,87285b34884572647811a353c7ac498a,29.99,utilidades_domesticas,housewares,4.0,"não testei produto ainda, mas ele veio correto..."
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,595fac2a385ac33a80bd5114aec74eb8,118.70,perfumaria,perfumery,4.0,muito bom produto.
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,aa4383b373c6aca5d8797843e5594415,159.90,automotivo,auto,NaN,NaN
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,d0b61bfb1de832b15ba9d266ca96e5b0,45.00,pet_shop,pet_shop,5.0,produto foi exatamente que eu esperava estava ...
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,65266b2da20d04dbe00c5c2d3bb7859e,19.90,papelaria,stationery,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
112814,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,f1d4ce8c6dd66c47bbaa8c6781c2a923,174.90,bebes,baby,4.0,so uma peça que veio rachado mas tudo bem rs
112815,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,b80910977a37536adeddd63663f916ad,205.99,eletrodomesticos_2,home_appliances_2,5.0,foi entregue antes do prazo.
112816,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,d1c427060a0f73f6b889a5c7c61f2ac4,179.99,informatica_acessorios,computers_accessories,2.0,foi entregue somente 1. quero saber do outro p...
112817,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,d1c427060a0f73f6b889a5c7c61f2ac4,179.99,informatica_acessorios,computers_accessories,2.0,foi entregue somente 1. quero saber do outro p...
112818,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,006619bbed68b000c8ba3f8725d5409e,68.50,beleza_saude,health_beauty,NaN,NaN

In [43]:
master=master[master['order_status']=='delivered']
master=master.dropna(subset=['product_category_name_english'])
master['comment']=master['comment'].fillna('sem comentários')

In [44]:
master

,order_id,customer_id,order_status,order_purchase_timestamp,product_id,price,product_category_name,product_category_name_english,score,comment
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,87285b34884572647811a353c7ac498a,29.99,utilidades_domesticas,housewares,4.0,"não testei produto ainda, mas ele veio correto..."
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,595fac2a385ac33a80bd5114aec74eb8,118.70,perfumaria,perfumery,4.0,muito bom produto.
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,aa4383b373c6aca5d8797843e5594415,159.90,automotivo,auto,NaN,sem comentários
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,d0b61bfb1de832b15ba9d266ca96e5b0,45.00,pet_shop,pet_shop,5.0,produto foi exatamente que eu esperava estava ...
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,65266b2da20d04dbe00c5c2d3bb7859e,19.90,papelaria,stationery,NaN,sem comentários
...,...,...,...,...,...,...,...,...,...,...
112814,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,f1d4ce8c6dd66c47bbaa8c6781c2a923,174.90,bebes,baby,4.0,so uma peça que veio rachado mas tudo bem rs
112815,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,b80910977a37536adeddd63663f916ad,205.99,eletrodomesticos_2,home_appliances_2,5.0,foi entregue antes do prazo.
112816,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,d1c427060a0f73f6b889a5c7c61f2ac4,179.99,informatica_acessorios,computers_accessories,2.0,foi entregue somente 1. quero saber do outro p...
112817,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,d1c427060a0f73f6b889a5c7c61f2ac4,179.99,informatica_acessorios,computers_accessories,2.0,foi entregue somente 1. quero saber do outro p...
112818,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,006619bbed68b000c8ba3f8725d5409e,68.50,beleza_saude,health_beauty,NaN,sem comentários

In [45]:
master['order_purchase_timestamp']=pd.to_datetime(master['order_purchase_timestamp'])

In [46]:
master['month']=master['order_purchase_timestamp'].dt.month
master['year']=master['order_purchase_timestamp'].dt.year
master['year_month']=master['order_purchase_timestamp'].dt.to_period('M')

In [47]:
master.to_csv(r'D:\ai_customer_intelligence\data\master_table_dataset.csv',index=False)

In [48]:
master.shape

(108799, 13)

In [49]:
master.head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,product_id,price,product_category_name,product_category_name_english,score,comment,month,year,year_month
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,87285b34884572647811a353c7ac498a,29.99,utilidades_domesticas,housewares,4.0,"não testei produto ainda, mas ele veio correto...",10,2017,2017-10
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,595fac2a385ac33a80bd5114aec74eb8,118.70,perfumaria,perfumery,4.0,muito bom produto.,7,2018,2018-07
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,aa4383b373c6aca5d8797843e5594415,159.90,automotivo,auto,NaN,sem comentários,8,2018,2018-08
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,d0b61bfb1de832b15ba9d266ca96e5b0,45.00,pet_shop,pet_shop,5.0,produto foi exatamente que eu esperava estava ...,11,2017,2017-11
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,65266b2da20d04dbe00c5c2d3bb7859e,19.90,papelaria,stationery,NaN,sem comentários,2,2018,2018-02
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,060cb19345d90064d1015407193c233d,147.90,automotivo,auto,NaN,sem comentários,7,2017,2017-07
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,4520766ec412348b8d4caa5e8a18c464,59.99,automotivo,auto,NaN,sem comentários,5,2017,2017-05
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,ac1789e492dcd698c5c10b97a671243a,19.90,moveis_decoracao,furniture_decor,NaN,sem comentários,1,2017,2017-01
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,9a78fb9862b10749a117f7fc3c31f051,149.99,moveis_escritorio,office_furniture,NaN,sem comentários,7,2017,2017-07
10,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,08574b074924071f4e201e151b152b4e,99.00,ferramentas_jardim,garden_tools,1.0,aguardando retorno da loja,5,2017,2017-05

In [50]:
master.info()

<class 'pandas.core.frame.DataFrame'>
Index: 108799 entries, 0 to 112818
Data columns (total 13 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       108799 non-null  object
 1   customer_id                    108799 non-null  object
 2   order_status                   108799 non-null  object
 3   order_purchase_timestamp       108799 non-null  datetime64[ns]
 4   product_id                     108799 non-null  object
 5   price                          108799 non-null  float64
 6   product_category_name          108799 non-null  object
 7   product_category_name_english  108799 non-null  object
 8   score                          45201 non-null   float64
 9   comment                        108799 non-null  object
 10  month                          108799 non-null  int32
 11  year                           108799 non-null  int32
 12  year_month                     108799 non-null  period[M]
dtypes: datetime64[ns](1), float64(2), int32(2), object(7), period[M](1)
memory usage: 10.8+ MB