In [108]:
import pandas as pd
df=pd.read_csv(r"D:\ai_customer_intelligence\data\olist_order_reviews_dataset.csv")

In [109]:
df=df[['order_id','review_score','review_comment_message']]

In [110]:
df=df.dropna(subset=['review_comment_message'])

In [111]:
df

,order_id,review_score,review_comment_message
3,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.
4,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...
9,b9bf720beb4ab3728760088589c62129,4,aparelho eficiente. no site a marca do aparelh...
12,9d6f15f95d01e79bd1349cc208361f09,4,"Mas um pouco ,travando...pelo valor ta Boa.\r\n"
15,e51478e7e277a83743b6f9991dbfa3fb,5,"Vendedor confiável, produto ok e entrega antes..."
...,...,...,...
99205,d398e9c82363c12527f71801bf0e6100,4,para este produto recebi de acordo com a compr...
99208,509b86c65fe4e2ad5b96408cfef9755e,5,Entregou dentro do prazo. O produto chegou em ...
99215,d5cb12269711bd1eaf7eed8fd32a7c95,3,"O produto não foi enviado com NF, não existe v..."
99221,55d4004744368f5571d1f590031933e4,5,"Excelente mochila, entrega super rápida. Super..."
99223,90531360ecb1eec2a1fbb265a0db0508,1,"meu produto chegou e ja tenho que devolver, po..."

In [112]:
df['review_clean'] = df['review_comment_message'].str.lower()

In [113]:
df

,order_id,review_score,review_comment_message,review_clean
3,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.,recebi bem antes do prazo estipulado.
4,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...,parabéns lojas lannister adorei comprar pela i...
9,b9bf720beb4ab3728760088589c62129,4,aparelho eficiente. no site a marca do aparelh...,aparelho eficiente. no site a marca do aparelh...
12,9d6f15f95d01e79bd1349cc208361f09,4,"Mas um pouco ,travando...pelo valor ta Boa.\r\n","mas um pouco ,travando...pelo valor ta boa.\r\n"
15,e51478e7e277a83743b6f9991dbfa3fb,5,"Vendedor confiável, produto ok e entrega antes...","vendedor confiável, produto ok e entrega antes..."
...,...,...,...,...
99205,d398e9c82363c12527f71801bf0e6100,4,para este produto recebi de acordo com a compr...,para este produto recebi de acordo com a compr...
99208,509b86c65fe4e2ad5b96408cfef9755e,5,Entregou dentro do prazo. O produto chegou em ...,entregou dentro do prazo. o produto chegou em ...
99215,d5cb12269711bd1eaf7eed8fd32a7c95,3,"O produto não foi enviado com NF, não existe v...","o produto não foi enviado com nf, não existe v..."
99221,55d4004744368f5571d1f590031933e4,5,"Excelente mochila, entrega super rápida. Super...","excelente mochila, entrega super rápida. super..."
99223,90531360ecb1eec2a1fbb265a0db0508,1,"meu produto chegou e ja tenho que devolver, po...","meu produto chegou e ja tenho que devolver, po..."

In [114]:
import re

def clean_review(text):
    text = text.strip()  # remove extra spaces
    
    # Check if text contains at least one alphabet (Portuguese included)
    if re.search(r'[a-zà-ú]', text):
        return text
    else:
        return None

In [115]:
df['review_clean'] = df['review_clean'].apply(clean_review)

In [116]:
df = df[df['review_clean'].notna()]

In [117]:
df

,order_id,review_score,review_comment_message,review_clean
3,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.,recebi bem antes do prazo estipulado.
4,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...,parabéns lojas lannister adorei comprar pela i...
9,b9bf720beb4ab3728760088589c62129,4,aparelho eficiente. no site a marca do aparelh...,aparelho eficiente. no site a marca do aparelh...
12,9d6f15f95d01e79bd1349cc208361f09,4,"Mas um pouco ,travando...pelo valor ta Boa.\r\n","mas um pouco ,travando...pelo valor ta boa."
15,e51478e7e277a83743b6f9991dbfa3fb,5,"Vendedor confiável, produto ok e entrega antes...","vendedor confiável, produto ok e entrega antes..."
...,...,...,...,...
99205,d398e9c82363c12527f71801bf0e6100,4,para este produto recebi de acordo com a compr...,para este produto recebi de acordo com a compr...
99208,509b86c65fe4e2ad5b96408cfef9755e,5,Entregou dentro do prazo. O produto chegou em ...,entregou dentro do prazo. o produto chegou em ...
99215,d5cb12269711bd1eaf7eed8fd32a7c95,3,"O produto não foi enviado com NF, não existe v...","o produto não foi enviado com nf, não existe v..."
99221,55d4004744368f5571d1f590031933e4,5,"Excelente mochila, entrega super rápida. Super...","excelente mochila, entrega super rápida. super..."
99223,90531360ecb1eec2a1fbb265a0db0508,1,"meu produto chegou e ja tenho que devolver, po...","meu produto chegou e ja tenho que devolver, po..."

In [118]:
print(df[['review_comment_message', 'review_clean']])

                                  review_comment_message  \
3                  Recebi bem antes do prazo estipulado.
4      Parabéns lojas lannister adorei comprar pela I...
9      aparelho eficiente. no site a marca do aparelh...
12       Mas um pouco ,travando...pelo valor ta Boa.\r\n
15     Vendedor confiável, produto ok e entrega antes...
...                                                  ...
99205  para este produto recebi de acordo com a compr...
99208  Entregou dentro do prazo. O produto chegou em ...
99215  O produto não foi enviado com NF, não existe v...
99221  Excelente mochila, entrega super rápida. Super...
99223  meu produto chegou e ja tenho que devolver, po...

                                            review_clean
3                  recebi bem antes do prazo estipulado.
4      parabéns lojas lannister adorei comprar pela i...
9      aparelho eficiente. no site a marca do aparelh...
12           mas um pouco ,travando...pelo valor ta boa.
15     vendedor confiável, produto ok e entrega antes...
...                                                  ...
99205  para este produto recebi de acordo com a compr...
99208  entregou dentro do prazo. o produto chegou em ...
99215  o produto não foi enviado com nf, não existe v...
99221  excelente mochila, entrega super rápida. super...
99223  meu produto chegou e ja tenho que devolver, po...

[40791 rows x 2 columns]

In [119]:
def remove_meaningless_token(text):
    words=text.split()
    cleaned_words=[]
    for word in words:
        if len(word)==1:  # remove single character
            continue
        if len(set(word))==1: # remove words with only one unique character
            continue
        cleaned_words.append(word)
    return " ".join(cleaned_words)

df['review_clean']=df['review_clean'].apply(remove_meaningless_token)

C:\Users\Asus\AppData\Local\Temp\ipykernel_18412\54986635.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review_clean']=df['review_clean'].apply(remove_meaningless_token)

In [120]:
df

,order_id,review_score,review_comment_message,review_clean
3,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.,recebi bem antes do prazo estipulado.
4,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...,parabéns lojas lannister adorei comprar pela i...
9,b9bf720beb4ab3728760088589c62129,4,aparelho eficiente. no site a marca do aparelh...,aparelho eficiente. no site marca do aparelho ...
12,9d6f15f95d01e79bd1349cc208361f09,4,"Mas um pouco ,travando...pelo valor ta Boa.\r\n","mas um pouco ,travando...pelo valor ta boa."
15,e51478e7e277a83743b6f9991dbfa3fb,5,"Vendedor confiável, produto ok e entrega antes...","vendedor confiável, produto ok entrega antes d..."
...,...,...,...,...
99205,d398e9c82363c12527f71801bf0e6100,4,para este produto recebi de acordo com a compr...,para este produto recebi de acordo com compra ...
99208,509b86c65fe4e2ad5b96408cfef9755e,5,Entregou dentro do prazo. O produto chegou em ...,entregou dentro do prazo. produto chegou em co...
99215,d5cb12269711bd1eaf7eed8fd32a7c95,3,"O produto não foi enviado com NF, não existe v...","produto não foi enviado com nf, não existe ven..."
99221,55d4004744368f5571d1f590031933e4,5,"Excelente mochila, entrega super rápida. Super...","excelente mochila, entrega super rápida. super..."
99223,90531360ecb1eec2a1fbb265a0db0508,1,"meu produto chegou e ja tenho que devolver, po...","meu produto chegou ja tenho que devolver, pois..."

In [121]:
import re

def normalize_elongated_words(text):
    # reduce repeated characters to max 2 occurrences
    text = re.sub(r'(.)\1{2,}', r'\1\1', text)
    return text

In [122]:
df['review_clean']=df['review_clean'].apply(normalize_elongated_words)

C:\Users\Asus\AppData\Local\Temp\ipykernel_18412\2538633940.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review_clean']=df['review_clean'].apply(normalize_elongated_words)

In [123]:
df

,order_id,review_score,review_comment_message,review_clean
3,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.,recebi bem antes do prazo estipulado.
4,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...,parabéns lojas lannister adorei comprar pela i...
9,b9bf720beb4ab3728760088589c62129,4,aparelho eficiente. no site a marca do aparelh...,aparelho eficiente. no site marca do aparelho ...
12,9d6f15f95d01e79bd1349cc208361f09,4,"Mas um pouco ,travando...pelo valor ta Boa.\r\n","mas um pouco ,travando..pelo valor ta boa."
15,e51478e7e277a83743b6f9991dbfa3fb,5,"Vendedor confiável, produto ok e entrega antes...","vendedor confiável, produto ok entrega antes d..."
...,...,...,...,...
99205,d398e9c82363c12527f71801bf0e6100,4,para este produto recebi de acordo com a compr...,para este produto recebi de acordo com compra ...
99208,509b86c65fe4e2ad5b96408cfef9755e,5,Entregou dentro do prazo. O produto chegou em ...,entregou dentro do prazo. produto chegou em co...
99215,d5cb12269711bd1eaf7eed8fd32a7c95,3,"O produto não foi enviado com NF, não existe v...","produto não foi enviado com nf, não existe ven..."
99221,55d4004744368f5571d1f590031933e4,5,"Excelente mochila, entrega super rápida. Super...","excelente mochila, entrega super rápida. super..."
99223,90531360ecb1eec2a1fbb265a0db0508,1,"meu produto chegou e ja tenho que devolver, po...","meu produto chegou ja tenho que devolver, pois..."

In [124]:
df.to_csv(r"D:\ai_customer_intelligence\data\cleaned_reviews_dataset.csv",index=False)

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40791 entries, 3 to 99223
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                40791 non-null  object
 1   review_score            40791 non-null  int64
 2   review_comment_message  40791 non-null  object
 3   review_clean            40791 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.6+ MB

In [126]:
df.describe()

       review_score
count  40791.000000
mean       3.666667
std        1.616951
min        1.000000
25%        2.000000
50%        5.000000
75%        5.000000
max        5.000000